Add json parser exercise
HamedNourani/Exercises pull request #1
Opened 2023-10-09 11:11 UTC by HamedNourani

2023-10-09 11:12 UTC, URAmiRBin commented
Ill review this

2023-10-09 11:13 UTC, URAmiRBin reviewed
Only add the csharp files

2023-10-14 08:29 UTC, URAmiRBin requested changes

2023-10-14 08:29 UTC, URAmiRBin commented on Algorithms and Data Structures/JasonConvertExercise/JasonConvertExercise/PlayerData.cs
> +﻿namespace JasonParserExercise
the namespace name should be `JsonParser`

2023-10-14 08:29 UTC, URAmiRBin commented on Algorithms and Data Structures/JasonConvertExercise/JasonConvertExercise/Program.cs
> +                }
the default values should be handled better, think about we want to have multiple default values for each field, multiple ifs is code smell and should indicate that you have to find a better way to solve this problem

2023-10-14 08:29 UTC, URAmiRBin commented on Algorithms and Data Structures/JasonConvertExercise/JasonConvertExercise/PlayerData.cs
> +        public int level;
the exercise says this: 

> Create a C# class named PlayerData that can represent the player's information, including fields for username, level, guild, items, and skinId. The class should also include appropriate properties and constructors.

where are the other properties?

2023-10-14 09:24 UTC, HamedNourani commented
@URAmiRBin 
I resolved the issues you had requested.

2023-10-14 09:48 UTC, URAmiRBin approved these changes

2023-10-14 09:48 UTC, merged